/* #undef ENABLE_NEW_ALLOCATOR */
#define HAVE_BITMAP_ALLOCATOR 1
#define HAVE_BOOST_FAST_POOL_ALLOCATOR 1
#define HAVE_BOOST_POOL_ALLOCATOR 1
#define HAVE_MT_ALLOCATOR 1
#define HAVE_POOL_ALLOCATOR 1
